### PR TITLE
added some CMIP6 monthly Ocean historical datasets

### PR DESCRIPTION
**Pull request by naomi-henderson**
Here is a new catalog for about 1.7Tb of zarr(consolidated) CMIP6 ocean data I have just uploaded to the pangeo-data gc bucket.

 There are too many datasets to just add to the existing `cmip6.yaml`, so instead I have nested `cmip6_Omon.yaml` (Omon = monthly ocean data) and `cmip6_A3hr.yaml` (A3hr = 3 hourly atmosphere data) into cmip6.yaml. 

I have left the original 3hourly data in `cmip6.yaml`, so existing notebooks should still work. The `master.yaml` has not been changed.

### CODE REVIEW

**Comment by rabernat** [comment]
@naomi-henderson - thanks for this! I'm just coming back to it now.

I wouldn't worry about breaking existing examples...we can always point them back to a specific commit.

Could you please move everything to sub-catalogs and create a link to cmip6 in the master catalog?

**Comment by naomi-henderson** [comment]
@rabernat - the master catalog is unchanged, still has a link to cmip6. What I did was to make the sub-catalog cmip6.yaml refer to two sub-sub-catalogs and then I left the original contents in cmip6.yaml  also (for existing examples).  So would you suggest I go ahead with the sub-sub-catalogs or just put everything in the cmip6.yaml?

**Comment by rabernat** [comment]
Ok I see. What I'm confused about is why the none of the CMIP datasets are getting check by the tests on travis:
https://travis-ci.org/pangeo-data/pangeo-datastore/jobs/512808097

**Comment by rabernat** [comment]
@naomi-henderson - could you rebase your branch on master? I did some cleanup to the validation routines in #20, and I want to see this run on your new catalogs.

**Comment by rabernat** [comment]
As you can see from the latest run of the tests, none of the current CMIP6 datasets appear to be working:
https://travis-ci.org/pangeo-data/pangeo-datastore/jobs/514773881#L600

So either there is a problem with the tests or with the datasets.

**Comment by rabernat** [comment]
@naomi-henderson - I figured out the issue: we need to add a `depth` parameter to `walk` when crawling down the catalogs. 

For the future, best not to make PRs from your master branch. Better to use a [feature branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) instead.

**Comment by rabernat** [comment]
Ok so the tests finally ran.

All of the cmip dataset entries are failing.

Any idea what's going on?

**Comment by naomi-henderson** [comment]
So it looks like the sub-sub catalogs aren't working any more. Would it be better if we just had cmip6.yaml contain ALL of the entries for now?

**Comment by rabernat** [comment]
Maybe this is related to the fact that there are '.' characters in the dataset names. Perhaps this is interfering with intake's ability to dive into a nested catalog.

With nested catalogs, we can do
```python
cat['ocean.SOSE']
```
and get back the correct entry. 

However
```python
cat['cmip6.A3hr.IPSL-CM6A-LR.historical.r7i1p1f1.tas']
```
returns `None`.

Pinging @martindurant for some intake advice.

**Comment by rabernat** [comment]
Yes, I think that is right. The following works
```python
cat_omon = cat['cmip6.Omon']
cat_omon['GISS-E2-1-G.historical.r1i1p1f1.wo']
```

**Comment by naomi-henderson** [comment]
I think perhaps it is the '-', not the '.'   I could rename all of the model names with '_' instead of '-'.  I already renamed the standard CMIP6 directory name of 3hr to A3hr, because dir entries cannot start with a number.  I will give it a try.

**Comment by rabernat** [comment]
Let's see what Martin says before we do anything else. I opened an intake issue.

**Comment by martindurant** [comment]
I sketched in the linked intake issue how I think the catalog getitem should work. I'm unlikely to get the time to implement anything this week, others are very welcome to try :)

**Comment by rabernat** [comment]
@naomi-henderson - I think the latest test results confirm that the problem is not the `-` character.

Progress on this requires changes to intake, so at this point I would say we just move forward and accept the failing tests.

**Comment by martindurant** [comment]
Thank you, by the way, for probing the corners of Intake usage!

**Pull request merged**
