### PR TITLE
Add GPM dataset

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
It looks like the GPM dataset is too slow to load. Is it because it doesn't have consolidated metadata?

**Comment by rabernat** [comment]
Yes that is probably why. Do you know how to apply consolidation?

**Comment by davidbrochart** [comment]
I would just open the zarr and save it again using `to_zarr(consolidated=True)`?
But I run out of memory when opening the zarr on my laptop. I created this zarr incrementally by appending to it.

**Comment by rabernat** [comment]
> I would just open the zarr and save it again using `to_zarr(consolidated=True)`?

That's a highly inefficient way to do it!

Here is a notebook with some examples. https://gist.github.com/rabernat/ce1fb414cf53541afe2245363b06c49d

Basically, you do something like this
```python
import zarr
import gcsfs
gcs_path = 'pangeo-data/gpm_imerg_early'
gcsfs = gcsfs.GCSFilesystem(...)
gcmap = gcsfs.GCSMap(gcs_path, gcs=gcs)
zarr.consolidate_metadata(gcsmap)
```

This only deals with the metadata and leaves the data untouched.

**Comment by rabernat** [comment]
Your dataset is also crashing the travis build. https://travis-ci.org/pangeo-data/pangeo-datastore/builds/516526115?utm_source=github_status&utm_medium=notification

There is something weird going on here.

Can you show me the xarray repr of the dataset before you write it to zarr?

**Comment by davidbrochart** [comment]
That's the problem, I cannot even open the zarr on my laptop, and it has been created using [this script](https://github.com/davidbrochart/pangeo_upload/blob/master/py/gpm2pangeo.py), where I did the following:
1) download 4 arrays from NASA's FTP server
2) create an initial zarr archive, or append the arrays to the existing archive along the time dimension
3) go to 1

This results in having 2697218 files (chunks) in the `pangeo-data/gpm_imerg_early/precipitationCal` directory. I remember a conversion on gitter where you were saying that the chunks are too small, maybe this is the issue? But I don't understand why we would need to open the chunk files.

I was able to open the zarr on the pangeo binder, here is the xarray repr of the dataset:
```
<xarray.Dataset>
Dimensions:           (lat: 1800, lon: 3600, time: 84288)
Coordinates:
  * lat               (lat) float32 -89.95 -89.85 -89.75 ... 89.75 89.85 89.95
  * lon               (lon) float32 -179.95 -179.85 -179.75 ... 179.85 179.95
  * time              (time) datetime64[ns] 2014-03-12T00:15:00 ... 2018-12-31T23:45:00
Data variables:
    precipitationCal  (time, lat, lon) float32 dask.array<shape=(84288, 1800, 3600), chunksize=(1, 225, 900)>
```

**Comment by rabernat** [comment]
Dask allocates a small amount of memory for each task. If there are millions of chunks, it can get messy.

Can you open the zarr dataset with `auto_chunk=False`?

**Comment by rabernat** [comment]
And yes, your chunks are much too small to be efficient in the cloud. There is a ~100 ms overhead associated with every read from cloud storage. Your chunks need to be > 10 MB in order to amortize this overhead. Instead, yours are 10-100 KB (https://console.cloud.google.com/storage/browser/pangeo-data/gpm_imerg_early/precipitationCal/).

You should call `ds.chunk(...)` after creating your dataset to rechunk the original dataset into larger chunks.

**Comment by rabernat** [comment]
I just tried `auto_chunk=False` and it opened immediately. So this is definitely the problem.

**Comment by davidbrochart** [comment]
For me `auto_chunk=False` doesn't solve the problem. And I still don't understand why Dask would have to look at the individual chunk files at that point. We didn't schedule any task yet, it should only open the metadata, right?
As far as the chunk size is concerned, that's an issue I've raised in https://github.com/pydata/xarray/pull/2706#issuecomment-459667067. When my initial zarr archive was created, I let zarr choose the chunk sizes. Maybe it made a choice according to the (small) size of the dataset. Then I append along the time dimension, and already the time array has a chunk size that cannot be greater than the total size in the initial zarr archive. And it may also affect the variable that has a time dimension.
In the GPM dataset, I re-chunked the time coordinate after I uploaded the whole thing, but I didn't touch the precipitationCal dataarray.

**Comment by rabernat** [comment]
> And I still don't understand why Dask would have to look at the individual chunk files at that point.

It does not "look" at the individual chunk files. (To be more specific, it does not perform any reads.) However, it does create a [task](http://docs.dask.org/en/latest/graphs.html) for each read, and puts the tasks together into a graph. The task is a "delayed" representation of the function call that must be executed in order to load the data. The graph is basically a python dictionary, and each task requires about [1 kB of memory](http://matthewrocklin.com/blog/work/2018/06/26/dask-scaling-limits). You can see the size of the graph by doing `len(ds.precipitationCal.data.dask)`. 

You have over two million tasks in your graph, before any computations are even added to it. It requires over 2GB of memory just to exist. This will not be a usable dask object.

The solution is to back up and change the process you are using to produce this dataset so that you have fewer, larger chunks.

**Comment by davidbrochart** [comment]
I see, so the `open_zarr` function already creates tasks for each read. I though it was only reading the metadata. Thanks for the explanation. I'm a bit worried then, because it doesn't really scale: even though we chunked our huge dataset, if we have too many chunks, Dask will have problems loading it. I guess it's a trade-off between network access time, complexity of the task graph, and memory size to hold the chunks.
I will try and rechunk my precipitationCal variable. It might once again schedule a huge amounts of tasks, but once it's done, further operations will be much smoother.

**Comment by rabernat** [comment]
Scaling is not a "yes or no" situation. Dask allows us to scale out computations that are much too big to fit on a single computer in an extremely flexible way. The price we pay for that flexibility is that the scalability is not infinite; if you have too many tasks in your graph, you start to hit new limits. @mrocklin  has a helpful blog post on this: http://matthewrocklin.com/blog/work/2018/06/26/dask-scaling-limits.

Your dataset is about 2TB in size. This is big enough that you have to be a bit thoughtful, but far from impossible. Many of us are working with datasets that size every day, but **we are using much bigger chunks** (like 100 MB). I'm sorry to keep repeating that point, but it is the only solution I know of right now.

> I guess it's a trade-off between network access time, complexity of the task graph, and memory size to hold the chunks.

Exactly! Well said.

> I will try and rechunk my precipitationCal variable. It might once again schedule a huge amounts of tasks, but once it's done, further operations will be much smoother.

Ideally you could avoid ever creating the small chunks. But I don't think the chunks can be smaller than your individual file size. Do you have over 2 million files?

**Comment by rabernat** [comment]
An alternative that works now is to simply use smaller chunks on reading:
```python
ds = xr.open_zarr(gcsfs.GCSMap('pangeo-data/gpm_imerg_early'), consolidated=True, auto_chunk=False).chunk({'time': 5})
```

This works ok. Now we have much fewer dask chunks. However, each dask task needs to make many reads to GCS, so the access is relatively slow (but not horrible).

Once https://github.com/pydata/xarray/pull/2530 is merged, we will be able to specify `chunks` as a keyword argument to `open_zarr`.

**Comment by davidbrochart** [comment]
You're right, each file is about 25MB big (1800*3600*4/1024/1024), so having a chunk of 4 of them seems reasonable. I'll upload again with this chunk size, and I will come back to this PR once it's done.
Also, thanks for the workaround, and your patience in taking time to explain!

**Comment by rabernat** [comment]
I am so glad we have this datastore repo to actually communicate about these obscure yet important points!

Although it can be frustrating, bear in mind that we are really breaking new ground here! You are at the vanguard of cloud-native data science.

**Comment by davidbrochart** [comment]
Not frustrating at all, I was just blindly assuming that everything should magically work perfectly. Well actually, it could have, if zarr had chosen by default to have this chunk of (4, 1800, 3600), because I had exactly this shape in memory before the first `to_zarr`. Maybe we should change its default settings?

**Comment by rabernat** [comment]
> Maybe we should change its default settings?

I'm puzzled about this, because dask's [default chunk size](https://docs.dask.org/en/latest/configuration.html#api) is 128 MiB.

**Comment by davidbrochart** [comment]
Maybe I'm missing something, but:

```python
import xarray as xr
import numpy as np

da = xr.DataArray(np.arange(4*1800*3600).reshape(4, 1800, 3600).astype('float32'))
ds = da.to_dataset(name='da')
ds.to_zarr('ds')
ds = xr.open_zarr('ds')
ds
```

```
<xarray.Dataset>
Dimensions:  (dim_0: 4, dim_1: 1800, dim_2: 3600)
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    da       (dim_0, dim_1, dim_2) float32 dask.array<shape=(4, 1800, 3600), chunksize=(1, 225, 900)>
```

Where each chunk's size is 1 * 225 * 900 * 4 / 1024 / 1024 = 0.77 MiB.

**Comment by davidbrochart** [comment]
I get different chunks when I don't use xarray:
```python
import numpy as np
import dask.array as da

d = np.arange(4*1800*3600).reshape(4, 1800, 3600).astype('float32')
x = da.from_array(d)
x
```

```
dask.array<array, shape=(4, 1800, 3600), dtype=float32, chunksize=(4, 900, 1200)>
```
Where each chunk's size is 4 * 900 * 1200 * 4 / 1024 / 1024 = 16 MiB.

**Comment by rabernat** [comment]
Ok so here we are confusing _Dask's_ automatic chunking heuristics with _Zarr's_ automatic chunking heuristics. (Either way, xarray has nothing to do with it.)

In your [first example](https://github.com/pangeo-data/pangeo-datastore/pull/24#issuecomment-481550282), Dask is not involved at all. It's Zarr that is deciding the chunk size (see [Zarr tutorial](https://zarr.readthedocs.io/en/stable/tutorial.html#chunk-optimizations)), and its heuristics produce a smaller chunk size.

Your [second example](https://github.com/pangeo-data/pangeo-datastore/pull/24#issuecomment-481616547) does not involve Zarr at all! Furthermore, you are not specifying any chunks, so you just get one global chunk. Dask does not automatically chunk anything by default. However, you can ask it to by passing `chunks='auto'` to its array creation methods.

Here's how xarray determines the zarr chunks to use. If it funds a `chunks` parameter in the variable `encoding` dictionary, it always uses that. If encoding is empty but the variable is a dask array, it uses the dask chunks for the zarr chunks. If neither is present, it writes to zarr without any chunks specified, and zarr's built-in heuristics determine the chunk size.

In writing that down, I realized that none of this is in the xarray documentation. :(

**Comment by davidbrochart** [comment]
Thanks, I understand better now. I edited the [second example](https://github.com/pangeo-data/pangeo-datastore/pull/24#issuecomment-481616547) because I forgot the `chunks='auto'` parameter (bad copy/paste).

**Comment by davidbrochart** [comment]
Still, it's strange that in the [second example](https://github.com/pangeo-data/pangeo-datastore/pull/24#issuecomment-481616547) the chunk size is 16 MiB and not 128 MiB.

**Comment by mrocklin** [comment]
If I may, I think that this should be resolved in this line:

    ds = xr.open_zarr('ds')

I think that Xarray should notice that Zarr's chunking is too fine, and increase chunking appropriately.  At least on local disk, it's probably reasonable for Zarr to have much smaller chunks than would be appropriate for Dask.  Probably Xarray should include a few Zarr chunks in a single Dask chunk.

**Comment by rabernat** [comment]
That's a reasonable suggestion Matt. However, I would be worried about baking too many assumptions into xarray. Both Dask and Zarr have their own chunking heuristics. Do we really want to have a third set of heuristics in xarray?

What if we could say
```
ds = xr.open_zarr('ds', chunks='auto')
```
and have the `chunks='auto'` passed to Dask? Could Dask then make a "good" decision about chunks. The challenge would be to align the dask chunks with the zarr chunks in an optimal way (i.e. many Zarr chunks --> one Dask chunk). Is there any logic like that already in Dask?

I encourage those interested in this topic to visit https://github.com/pydata/xarray/pull/2530, where @lilyminium is working on revamping how xarray handles zarr / dask chunks.

**Comment by mrocklin** [comment]
Yes, you'll want to use the `dask.array.core.normalize_chunks` function.


```python
In [1]: from dask.array.core import normalize_chunks

In [2]: normalize_chunks('auto', shape=(10000, 10000), limit='64 MiB', dtype='float64', previous_chunks=(10, 20))
Out[2]: ((2040, 2040, 2040, 2040, 1840), (4080, 4080, 1840))
```

In that example I've used some values that would come from the Zarr array.  I also used '64 MiB', but probably I should have checked Dask's configuration instead.

```python
In [3]: import dask

In [4]: dask.config.config
Out[4]: {'array': {'chunk-size': '128MiB', 'rechunk-threshold': 4}}

In [5]: dask.config.get('array.chunk-size')
Out[5]: '128MiB'
```

**Comment by alimanfoo** [comment]
FWIW zarr's heuristics for guessing chunk size are very crude and will be
suboptimal in most cases either because chunk size or chunk shape are not
appropriate.

Matt's suggestion to include multiple zarr chunks on one dask chunk is a
good workaround if you have to work with an existing zarr dataset where you
don't have control over chunking. But if you are making a new zarr dataset
then I would suggest tuning chunks so they are larger.

**Comment by davidbrochart** [comment]
@rabernat I uploaded a new GPM dataset to GCS, it looks good now. I don't know how to trigger the Travis build though.

**Comment by rabernat** [comment]
Awesome, this works now! The test failures are not related to your dataset.

I would love if you cold write up something about what you're doing here. AFAIK, this is one of the first examples of a continuously extended Zarr datasets. It would be of enormous value to the Pangeo community to have some details about how it was accomplished.

You have an open invitation to write a blog post for the Pangeo medium blog.

**Comment by davidbrochart** [comment]
Thanks a lot @rabernat, I will think about it seriously.

**Comment by davidbrochart** [comment]
@rabernat I wrote a blog post, please let me know what you think: https://github.com/davidbrochart/pangeo_upload/blob/master/blog_post.md

**Comment by alimanfoo** [comment]
Very nice blog post!

**Comment by rabernat** [comment]
@davidbrochart this post is awesome! Thank you so much for writing it.

It would be great to add
- the xarray repr of the dataset (just to give people some idea of what is in your dataset)
- a plot of a single snapshot (people love figures)

Then we will have to figure out how to import it into our medium blog.

**Comment by davidbrochart** [comment]
@rabernat done.

**Comment by rabernat** [comment]
Looks great!

Are you https://medium.com/@david.brochart? If so, I have added you to the Pangeo blog.

Then you can use this -- https://markdowntomedium.com/create -- to import your story. 

Ping me when you have the draft ready on medium.

**Comment by davidbrochart** [comment]
Yes, it looks like me (didn't remember I had an account).
The draft is ready.

**Comment by rabernat** [comment]
Looks great! You should have an option to "add" the story to the Pangeo publication. Do you see that? Can you try it?

**Comment by davidbrochart** [comment]
No, when I click on "Add to publication" I get "No publications available". I also have no sign of being added to the Pangeo blog.

**Comment by rabernat** [comment]
Can you try again? I just re-added you as an author.

**Comment by davidbrochart** [comment]
It works.

**Pull request merged**
