### PR TITLE
Added TRACMIP catalog to Pangeo Atmos catalog

### PR DESCRIPTION
**Pull request by charlesbluca**
This adds the TRACMIP (Tropical Rain belts with an Annual cycle and a Continent Model Intercomparison Project) data to Pangeo's Atmospheric Science Dataset Catalog; this is part of an overarching project to move the development of this project over to Pangeo's JupyterHub environment.

### CODE REVIEW

**Comment by naomi-henderson** [comment]
Catalog is looking great, @charlesbluca . I just happened to notice that there is an error for one of the zarr datasets:

`ValueError: conflicting sizes for dimension 'lat': length 89 on 'ua' and length 90 on 'cl'`

try:   

`cat['atmosphere.tracmip.Amon_aquaControl_GISS-ModelE2_v20190114'].to_dask()`

where cat is whatever you called the master intake catalog

**Comment by charlesbluca** [comment]
Good catch, Naomi! I'll probe through the catalog to see what other zarr datasets have similar issues.

**Comment by charlesbluca** [comment]
After reorganizing how the original data was converted and stored in the bucket, we shouldn't run into the previous issues we had with certain datasets being inaccessible (conflicting coordinate sizes).

**Comment by rabernat** [comment]
Ok so I understand why this not working. There are over 70,000 lines in the new catalog file.

Intake is not going to work here. We need to go with @naomi-henderson's CSV file approach.

**Pull request closed without merging**
