### PR TITLE
add CM2.6 ocean_budgets entries

### PR DESCRIPTION
**Pull request by raphaeldussin**

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks @raphaeldussin! cc @lufiedl.

**Comment by rabernat** [comment]
For some reason it looks like this broke the catalog!
http://catalog.pangeo.io/ocean

@charlesbluca - do you have any idea what's going on?

**Comment by charlesbluca** [comment]
Thanks for bringing this to my attention - think this might be an issue of whitespace in the new YAML file:

```
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    plugins:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 175, column 3:
      GFDL_CM2_6_grid:
      ^
```

**Comment by charlesbluca** [comment]
Merged in #84, looks like everything is working fine on the site now!

**Comment by raphaeldussin** [comment]
thanks for the fix! rookie mistake

**Pull request merged**
