### PR TITLE
Add radar altimetry products

### PR DESCRIPTION
**Pull request by fbriol**
The construction on Travis didn't work. XArray raises a "NotImplementedError" exception but not on my laptop. Perhaps the docker image is too old...

I had to make access to the Bucket public for my tests. If it's an issue, I can take it off.

While doing the tests on my catalog, I noticed that reading the dataset systematically retrieves the axis data on the PC. In the case of altimetry data, the time axis is relatively heavy to recover, as it represents one measurement every second over at least 5 years per mission. This represents 1GB of data to download for all missions. Maybe we would need an option in "xarray", not to read these data and leave them as a "dask" array.

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for this @fbriol! 

The test failures are not due to your additions. But we need to figure out what is going on...

**Comment by rabernat** [comment]
I care very much about this, but I don't have much time to spend right now debugging. If anyone else wants to sort out why the tests are failing, I would appreciate it sincerely.

Thinks will improve for me in December as our semesters winds down.

**Comment by rabernat** [comment]
@charlesbluca -- any objections to merging this?

**Comment by rabernat** [comment]
@charlesbluca - can you let us know whether it's okay to merge this despite the failing tests?

**Comment by charlesbluca** [comment]
Despite the failing tests, it looks like all the data is accessible -- this can be merged.

I noticed that bucket is not requester pays -- do we want to set it?

**Comment by rabernat** [comment]
> Despite the failing tests, it looks like all the data is accessible -- this can be merged.

Great! Please go ahead and merge. 😄 



> I noticed that bucket is not requester pays -- do we want to set it?

Yes, good idea. In general, all the buckets need to be requester pays. @fbriol -- this will likely require some slight changes to your `gsutil` command-line arguments and possibly privileges as well.

**Comment by charlesbluca** [comment]
Great! I just turned on requester pays, we'll have to add that into `storage_options` and also remove `token: anon`.

**Comment by charlesbluca** [comment]
For timing purposes, I'm just gonna merge this one and make those relevant alterations in a separate PR - thanks for the help @fbriol!

**Pull request merged**
